### ISSUE TITLE
Size field in discord message only shows "KB, MB or GB" but the actual file size doesn't come through

### ISSUE THREAD

**Issue by mdoh66** [uncapped1599/discord_qbittorrent#4]
The Discord messages that come through do show "KB, MB, or GB" but the actual file size number doesn't show up.

**Comment by uncapped1599** [comment]
Are you mapping it correctly from qBittorrent? Remember each number in the script needs to correspond to the parameter in qbit in the right sequence.

In my example, the script is triggered in qbit like so, with '%Z' being size. Hence '$2' being the size in the discord script:
```shell
/dropbox/scripts/discord_hoe_qbit_notification.sh "%N" "%Z" "%C" "%T" "%L" "%D"
``` 

What does yours look like and how are you testing?

**Comment by mdoh66** [comment]
Yes, I believe everything is mapped correctly, as everything else works.


Here is my qBittorrent line:
/config/torrent_after.sh "%N" "%Z" "%C" "%T" "%L" "%D"

and here is the script as configured:

#!/bin/bash


# Discord webhook details
discord_webhook_url="WEBHOOK URL"  # Update with your Discord webhook URL

# Get variables from qBitTorrent. Remember to make sure these align with
your qBittorrent variables passed in settings.
torrent_name="$1"
size="$2"
files="$3"
tracker="$4"
category="$5"
path="$6"

# Function to convert size from bytes to megabytes (MB)
calculate_size_in_mb() {
    size_in_mb=$(bc <<< "scale=2; $size / (1024 * 1024)")
    echo "$size_in_mb MB"
}

# Function to convert size from bytes to gigabytes (GB)
calculate_size_in_gb() {
    size_in_gb=$(bc <<< "scale=2; $size / (1024 * 1024 * 1024)")
    echo "$size_in_gb GB"
}

# Function to convert size from bytes to kilobytes (KB)
calculate_size_in_kb() {
    size_in_kb=$(bc <<< "scale=2; $size / 1024")
    echo "$size_in_kb KB"
}

# Determine download type based on the category.
# This is optional, only if you want to change the notification message
based on the category.
# You can also comment out this entire section and simply use $category in
the 'title' field of the payload below.
case "$category" in
    "audiobook")
        download_type="audiobook"
        ;;
    "ebooks")
        download_type="ebooks"
        ;;
    *)
        download_type="Uncategorised"
        ;;
esac

# Calculate the size message based on the size in megabytes, kilobytes, or
gigabytes
if (( size < 1024 * 1024 )); then
    size_message=$(calculate_size_in_kb)
elif (( size < 1024 * 1024 * 1024 )); then
    size_message=$(calculate_size_in_mb)
else
    size_message=$(calculate_size_in_gb)
fi

# Construct the JSON payload for Discord
# You can change the color of the left hand stripe of the notification
using the "color" field.
payload='{
    "embeds": [
        {
            "author": {
                "name": "qBittorrent",
                "icon_url": "https://i.imgur.com/6LTKLgZ.jpg"
            },
            "title": "'$download_type' torrent added.",
            "color": 7506394,
            "fields": [
                {
                    "name": "Torrent",
                    "value": "'$torrent_name'"
                },
                {
                    "name": "Size",
                    "value": "'$size_message'",
                    "inline": true
                },
                {
                    "name": "Files",
                    "value": "'$files'",
                    "inline": true
                },
                {
                    "name": "Tracker",
                    "value": "'$tracker'"
                },
                {
                    "name": "Save Path",
                    "value": "'$path'"
                }
            ]
        }
    ]
}'

# Function to send a notification to Discord
send_discord_notification() {
    curl -H "Content-Type: application/json" -X POST -d "$payload"
"$discord_webhook_url" >/dev/null 2>&1
}

# Send a notification to Discord
send_discord_notification

# Print an info message in the console
echo "[$torrent_name] ${download_type} completed. Discord notification
sent."

**Comment by mdoh66** [comment]
Issue is "bc" package is not installed in the docker container. Unfortunately doesn't seem like there is a way to reliably add this package and keep it, so not an issue with the script.

I was able to fix it by doing the math within the script itself instead of relying on the bc package.

# Function to convert size from bytes to megabytes (MB)
calculate_size_in_mb() {
    size_in_mb=$((size / (1024 * 1024)))
    echo "$size_in_mb MB"
}

# Function to convert size from bytes to gigabytes (GB)
calculate_size_in_gb() {
    size_in_gb=$((size / (1024 * 1024 * 1024)))
    echo "$size_in_gb GB"
}

# Function to convert size from bytes to kilobytes (KB)
calculate_size_in_kb() {
    size_in_kb=$((size / 1024))
    echo "$size_in_kb KB"
}

**Comment by uncapped1599** [comment]
Ah, nice and simple. May as well update the script with this. Thanks!
