### ISSUE TITLE
working example of "watched_folders.json"

### ISSUE THREAD

**Issue by danutzzzzz** [uncapped1599/discord_qbittorrent#5]
Hi, do you have a working example of `watched_folders.json`?

**Comment by uncapped1599** [comment]
Just pulled the one out of my working qBit docker container and have added to the repo.

**Comment by danutzzzzz** [comment]
Thanks, i realised yesterday that the linuxserver.io web version does populate this folder as there is a "watch folder" section in options that you can complete that then populates the `watched_folders.json` file.

**Comment by uncapped1599** [comment]
Indeed it does, what it won't do is surface the ability to add categories to the watch folders as I mention. You have to do that directly in the generated json file.
